### ISSUE TITLE
Multi-threading vs Async Programming in Rust

### ISSUE THREAD

**Issue by mohammadrajabraza** [mohammadrajabraza/class-codes-piaic-q3#1]
### Assignment Question
Differentiate between Multi-threading and Async Programming in rust. Support your arguments with examples. Also, implement scenarios to demonstrate both (i.e. multithreading and async) concepts.

### Requirements
Assignment text (i.e. differentiation arguments) should be in **.md** (markdown) file instead of **.txt**, **.docx** or **.pdf**

### Deadline
**Friday, Aug 20, 2021**

### Submission Method
Will be told in the coming class (**on 15th Aug**)

**Comment by rehantahirbutt** [comment]
got that..thank you

**Comment by AtaMustafa87** [comment]
got itt!

**Comment by tj-yazman** [comment]
Thanks Working for me

**Comment by mdawar-cs** [comment]
@mohammadrajabraza  Sir, I'm getting 403 error while pushing the assignment. I made my own repository and pushed on it.
https://github.com/mdawar-cs/PIAIC-IOT-Q3

**Comment by mohammadrajabraza** [comment]
https://github.com/mohammadrajabraza/react-routers-demo/issues/1
Refer to this issue

**Comment by YAHYA-YOUNAS** [comment]
While pushing, I am facing this error. Kindly help me out.
remote: Permission to mohammadrajabraza/class-codes-piaic-q3.git denied to YAHYA-YOUNAS.
fatal: unable to access 'https://github.com/mohammadrajabraza/class-codes-piaic-q3.git/': The requested URL returned error: 403

**Comment by mohammadrajabraza** [comment]
@YAHYA-YOUNAS @mdawar-cs refer to this issue for solution https://github.com/mohammadrajabraza/class-codes-piaic-q3/issues/5#issuecomment-900564469
