### ISSUE TITLE
Getting Error: Nothing to compare while creating Pull Request

### ISSUE THREAD

**Issue by rashidrasheed81** [mohammadrajabraza/class-codes-piaic-q3#17]
assalamu alaikum Sir, I clone the repo to my local system, make the changes in main and .md file, I update the local repo to my github repo but when i create pull request its saying nothing to compare. My repo link is https://github.com/rashidrasheed81/class-codes-piaic-q3.git . How to solve this problem.

**Comment by mohammadrajabraza** [comment]
In your local repository run `$ git log --oneline` and share screenshot of the output.

**Comment by rashidrasheed81** [comment]
Sir, screenshot is attached.
![Screen Shot 08-21-21 at 02 11 PM](https://user-images.githubusercontent.com/49232102/130319950-12721061-4523-4ad6-9644-ee262a35e73c.PNG)

**Comment by mohammadrajabraza** [comment]
Show the screenshot of the PR screen.

**Comment by rashidrasheed81** [comment]
![Screen Shot 08-21-21 at 03 51 PM 001](https://user-images.githubusercontent.com/49232102/130322382-cd3e189a-1f66-4f0b-90e5-34953e7a9559.PNG)
![Screen Shot 08-21-21 at 03 51 PM](https://user-images.githubusercontent.com/49232102/130322383-937761f5-5205-4203-ad39-1c862d9dfe87.PNG)

**Comment by mohammadrajabraza** [comment]
On the first screenshot, see what are the options appearing in **base: main** dropdown.

**Comment by rashidrasheed81** [comment]
![Screen Shot 08-21-21 at 05 57 PM](https://user-images.githubusercontent.com/49232102/130325876-bf245941-6e0b-405b-b3a5-fb9450ee26f2.PNG)
![Screen Shot 08-21-21 at 05 58 PM](https://user-images.githubusercontent.com/49232102/130325877-1458df8c-2212-4541-bdbc-28c23c21e427.PNG)

**Comment by shmlaiq** [comment]
push origin assign1/FaisalLaiq-PIAIC-87288
remote: Permission to mohammadrajabraza/class-codes-piaic-q3.git denied to shmlaiq.
fatal: unable to access 'https://github.com/mohammadrajabraza/class-codes-piaic-q3.git/': The requested URL returned error: 403
fysal@ubuntu:~/Assingments/class-codes-piaic-q3/assignment_1/src/class-codes-piaic-q3/assignment_1$ git push origin assign1/FaisalLaiq-PIAIC-87288
remote: Permission to mohammadrajabraza/class-codes-piaic-q3.git denied to shmlaiq.
fatal: unable to access 'https://github.com/mohammadrajabraza/class-codes-piaic-q3.git/': The requested URL returned error: 403
fysal@ubuntu:~/Assingments/class-codes-piaic-q3/assignment_1/src/class-codes-piaic-q3/assignment_1$ git push origin assign1/FaisalLaiq-PIAIC-87288
remote: Permission to mohammadrajabraza/class-codes-piaic-q3.git denied to shmlaiq.
fatal: unable to access 'https://github.com/mohammadrajabraza/class-codes-piaic-q3.git/': The requested URL returned error: 403

**Comment by mohammadrajabraza** [comment]
Closing it now because we have discussed it now
